# Generated by Django 5.2.6 on 2025-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите обложку книги')),
                ('quantity_page', models.PositiveIntegerField(default=1, verbose_name='Укажите количество страниц')),
                ('author', models.CharField(max_length=100, verbose_name='Укажите писателя')),
                ('audio_book', models.URLField(verbose_name='Ссылка на аудио книгу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
