# Generated by Django 5.2.6 on 2025-10-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_participants_tournaments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Участника', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='tournament_name',
            field=models.CharField(default='Матиматика', max_length=100),
        ),
    ]
