# Generated by Django 5.2.6 on 2025-10-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='Загрузите картинку фильма')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название фильма')),
                ('description', models.TextField(verbose_name='Укажите описание к фильму')),
                ('genre', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Фантастика', 'Фантастика'), ('Боевики', 'Боевики')], default='Фантастика', max_length=100)),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Укажите режисера')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Укажите количество серий')),
                ('trailer', models.URLField(verbose_name='Укажите ссылку с youtube')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
